import datetime

def get_month_week(dt=None):
    """
    Generated by Gemini AI. Yes. i wrote this manually.
    현재 시간 또는 입력된 datetime 객체의 월별 주차를 반환합니다.

    Args:
        dt (datetime.datetime, optional): 월별 주차를 계산할 datetime 객체. 기본값은 현재 시간.

    Returns:
        tuple: 월별 주차를 나타내는 튜플 (year, month, week).
    """
    if dt is None:
        dt = datetime.datetime.now()

    # 년도, 월
    year = dt.year
    month = dt.month

    # 해당 월의 첫날
    first_day_of_month = datetime.date(year, month, 1)

    # 입력된 날짜와 해당 월의 첫날 사이의 날짜 차이
    # (요일은 계산하지 않음)
    days_since_month_start = (dt.date() - first_day_of_month).days

    # 월별 주차 계산 (7일 단위로 나누기)
    week = days_since_month_start // 7 + 1

    return year, month, week
